version: "3.2"

services:
  node:
    build: .
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: blogs_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - blogs_api_net
  db:
    container_name: blogs_api_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    env_file:
      - .env.mysql
    networks:
      - blogs_api_net

networks:
  blogs_api_net: